export const ActionTypes = {
    REFERENTIAL: {
        LOAD_RACES: "LOAD_RACES",
        LOAD_SUB_RACES: "LOAD_SUB_RACES",
        LOAD_CLASSES: "LOAD_CLASSES",
        LOAD_CAPACITIES: "LOAD_CAPACITIES",
        LOAD_HISTORICS: "LOAD_HISTORICS",
        LOAD_WEAPON_CATEGORIES: "LOAD_WEAPON_CATEGORIES",
        LOAD_WEAPONS: "LOAD_WEAPONS",
        LOAD_ARMOR_CATEGORIES: "LOAD_ARMOR_CATEGORIES",
        LOAD_ARMORS: "LOAD_ARMORS",
        LOAD_OBJECT_CATEGORIES: "LOAD_OBJECT_CATEGORIES",
        LOAD_OBJECTS: "LOAD_OBJECTS",
        LOAD_EQUIPMENT_CATEGORIES: "LOAD_EqUIPMENT_CATEGORIES",
        LOAD_EQUIPMENTS: "LOAD_EQUIPMENTS",
        LOAD_HOSTEL_CATEGORIES: "LOAD_HOSTEL_CATEGORIES",
        LOAD_HOSTEL_SERVICES: "LOAD_HOSTEL_SERVICES",
        LOAD_SERVICE_CATEGORIES: "LOAD_SERVICE_CATEGORIES",
        LOAD_SERVICES: "LOAD_SERVICES",
        LOAD_MOUNTS: "LOAD_MOUNTS",
        LOAD_SHIPS: "LOAD_SHIPS",
        LOAD_WARES: "LOAD_WARES",
        LOAD_TRINKETS: "LOAD_TRINKETS",
        LOAD_LEVELS: "LOAD_LEVELS",
        LOAD_CARACTERISTICS: "LOAD_CARACTERISTICS",
        LOAD_SKILLS: "LOAD_SKILLS",
        LOAD_SPELLS: "LOAD_SPELLS",
        LOAD_ALTERATIONS: "LOAD_ALTERATIONS",
        LOAD_ALIGNMENTS: "LOAD_ALIGNMENTS",
        LOAD_LANGUAGES: "LOAD_LANGUAGES"
    },
    CHARACTERS: {
        LOAD: 'LOAD_CHARACTERS',
        LOAD_ONE: 'LOAD_ONE_CHARACTER'
    }
}