export const ActionTypes = {
    REFERENTIAL: {
        LOAD_RACES: "LOAD_RACES",
        LOAD_CLASSES: "LOAD_CLASSES",
        LOAD_WEAPON_CATEGORIES: "LOAD_WEAPON_CATEGORIES",
        LOAD_WEAPONS: "LOAD_WEAPONS",
        LOAD_LEVELS: "LOAD_LEVELS",
        LOAD_CARACTERISTICS: "LOAD_CARACTERISTICS",
        LOAD_SKILLS: "LOAD_SKILLS"
    },
    CHARACTERS: {
        LOAD: 'LOAD_CHARACTERS',
        LOAD_ONE: 'LOAD_ONE_CHARACTER',
        TOGGLE_SKILL: 'TOGGLE_SKILL'
    }
}